---
title: "Group Activity!"
author: "Pietro Franceschi"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
library(DiagrammeR)
```


```{css}

slides > slide {
  background: linear-gradient(#ffffff, #ffffff 85%, #ffffff);
  background-color: white;
}


#notes {
  color: blue;
}

del {
  color: red;
  text-decoration: none;
}

strong {
  color: #404040;
}

```
## Design your Study

* define the question
* define the experimental design 
* define the sample type, how to sample it and, maybe, give an estimate of the number of samples you think would be necessary
* define the analytical technique and the metabolomic approach
* propose a data-analysis approach

For each one of the previous points identify potential **challenges**


## Scenario 1

We would like to present a research project for a forthcoming EU call with the objective of studying what are the effects of global warming and pollution (zinc concentration) on the metabolism of the mediterranean mussel (_Mytilus galloprovincialis_)

## Scenario 2

Our research institute is interested in developing new varieties of grapevine, which are able to better withstand _Plasmopara viticola_ infection. The reduction of the use of chemicals is indeed one of the priorities of the new european regulations. 
Our colleagues has been setting up an extensive breeding program, but we would like to use metabolomics to perform an early screening of the potential genetic traits which are responsible of the resistance.


## Scenario 3

After hundreds of years, we would like to finally give a scientific support to the old belief that "eating carrots improves vision". Metabolomics could definitively help, both in the characterization of the carrots and in their effects on humans ...



