---
title: "Software Resources (also) For Preprocessing"
author: "Pietro Franceschi"
output: 
  ioslides_presentation:
    css: "../mycss.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(knitr)
library(webshot)
```



## Intro

Many of the steps we have been discussing today are common to almost all software solutions availabe for tha analysis of metabolomics data:

1. Commercial suites
2. Open source solutions which can be run locally (e.g. `xcms`,`MzMine`,`MSDial`)
3. Freely available web services


## `XCMS` Online

### 1 - Allow the use of xcms through a web interface

[`xcms` online](https://xcmsonline.scripps.edu/landing_page.php?pgcontent=mainPage)

### 2 - Allows to use xcms through Galaxy
The French metabolomics network also provide software for pathway analysis and visualization

[`Metabohub` - Workflow-4-metabolomics](https://workflow4metabolomics.org/)

## R based analysis

### Linked to the Human Metabolome Database
MetaboAnalyst	- statistical, functional and integrative analysis of metabolomics data

[`Metaboanalyst`](https://www.metaboanalyst.ca/)

## Without R

### Python Based
As part of the deNBI Center for integrative Bioinformatics, OpenMS offers an open-source software C++ library (+ python bindings) for LC/MS data management and analyses

[`OpenMS`](https://www.openms.de/)

### In Galaxy and Knime
KNIME Analytics Platform is the open source software for creating data science

[`knime`](https://www.knime.com/)

## The Phenomenal Project
PhenoMeNal (Phenome and Metabolome aNalysis) is a comprehensive and standardised e-infrastructure that supports the data processing and analysis pipelines for molecular phenotype data generated by metabolomics applications

[`PhenoMeNal`](https://phenomenal-h2020.eu/home/)


## Human Friendly Open Solutions

### MZmine
MZmine 3 is an open-source software for mass-spectrometry data processing, with the main focus on LC-MS data.

[`MZmine3`](https://mzmine.github.io/)

## MS-Dial
MS-DIAL was launched as a universal program for untargeted metabolomics that supports multiple instruments (GC/MS, GC/MS/MS, LC/MS, and LC/MS/MS) and MS vendors (Agilent, Bruker, LECO, Sciex, Shimadzu, Thermo, and Waters)

[`MS-Dial`](http://prime.psc.riken.jp/compms/msdial/main.html)





